# Generated by Django 3.2.8 on 2021-10-19 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0003_rename_content_context_context'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='context',
            table='Context',
        ),
    ]
