import mysql.connector
import datetime
db = mysql.connector.connect(
    host = "localhost",
    user="root",
    passwd = '123456',
    database="soliditycpn"
)
def InsertIMG(FilePath):
    with open(FilePath,"rb") as File :
        BinaryData = File.read()
    return BinaryData
mycursor = db.cursor()
sqlFomular = "INSERT INTO CheckedBatchSC (aid,lnid,lteid,cid,imid,noSC,checkedDate,status,LTLformula,result) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)"
multi = [
    (1,1,1,1,1,4,datetime.datetime.now(),True,"LTLformula 1","Helena report\n--------------------------------------------------------------------------------\n\n  General informations\n  ------------------------------------------------------------------------------\n    Model analyzed\n      EtherGame\n    Model parameters\n      N = 2\n      cb = 0\n      v1 = 3\n      v2 = 2\n      v3 = 5\n      v4 = 3\n      v5 = 10\n      v6 = 5\n      users = 1\n      play_sdr = 10\n      claimReward_sdr = 10\n    Model language\n      Helena\n    Analysis date\n      December, 24, 2021 at 16:46:25\n    Command used\n      /home/quypham/helena/bin/helena -N=CHECK -p=prop test.lna\n    File path\n      /home/quypham/SolidityProject/tools/unfolding/output/test.lna\n\n  Search report\n  ------------------------------------------------------------------------------\n    Action performed\n      property checking\n    Host machine\n      quypham (pid = 16631)\n    Property checked\n      prop\n    Termination state\n      PROPERTY_HOLDS\n    Options\n      Search algorithm = DFS\n      Partial order reduction = off\n      Hash compaction = off\n      State compression = off\n      Random successor selection = off\n      Hash table size = 4194304 states\n      Worker threads = 1\n\n  Statistics report\n  ------------------------------------------------------------------------------\n\n    Model statistics\n    ----------------------------------------------------------------------------\n      15 places\n      17 transitions\n      62 arcs\n\n    Time statistics\n    ----------------------------------------------------------------------------\n      3.06 s. for source compilation\n      0.04 s. for exploration\n\n    Exploration statistics\n    ----------------------------------------------------------------------------\n      10232 states stored\n      10232 states processed\n      0 accepting states\n      0 deadlock states\n      20463 transitions\n\n    Other statistics\n    ----------------------------------------------------------------------------\n      20463 events executed\n--------------------------------------------------------------------------------\n;"),
    (2,2,2,2,2,2,datetime.datetime.now(),False,"LTLformula 2","Helena report\n--------------------------------------------------------------------------------\n\n  General informations\n  ------------------------------------------------------------------------------\n    Model analyzed\n      EtherGame\n    Model parameters\n      N = 2\n      cb = 0\n      v1 = 3\n      v2 = 2\n      v3 = 5\n      v4 = 3\n      v5 = 10\n      v6 = 5\n      users = 1\n      play_sdr = 10\n      claimReward_sdr = 10\n    Model language\n      Helena\n    Analysis date\n      December, 24, 2021 at 16:46:25\n    Command used\n      /home/quypham/helena/bin/helena -N=CHECK -p=prop test.lna\n    File path\n      /home/quypham/SolidityProject/tools/unfolding/output/test.lna\n\n  Search report\n  ------------------------------------------------------------------------------\n    Action performed\n      property checking\n    Host machine\n      quypham (pid = 16631)\n    Property checked\n      prop\n    Termination state\n      PROPERTY_HOLDS\n    Options\n      Search algorithm = DFS\n      Partial order reduction = off\n      Hash compaction = off\n      State compression = off\n      Random successor selection = off\n      Hash table size = 4194304 states\n      Worker threads = 1\n\n  Statistics report\n  ------------------------------------------------------------------------------\n\n    Model statistics\n    ----------------------------------------------------------------------------\n      15 places\n      17 transitions\n      62 arcs\n\n    Time statistics\n    ----------------------------------------------------------------------------\n      3.06 s. for source compilation\n      0.04 s. for exploration\n\n    Exploration statistics\n    ----------------------------------------------------------------------------\n      10232 states stored\n      10232 states processed\n      0 accepting states\n      0 deadlock states\n      20463 transitions\n\n    Other statistics\n    ----------------------------------------------------------------------------\n      20463 events executed\n--------------------------------------------------------------------------------\n;"),
    (3,3,3,3,3,7,datetime.datetime.now(),True,"LTLformula 3","Helena report\n--------------------------------------------------------------------------------\n\n  General informations\n  ------------------------------------------------------------------------------\n    Model analyzed\n      EtherGame\n    Model parameters\n      N = 2\n      cb = 0\n      v1 = 3\n      v2 = 2\n      v3 = 5\n      v4 = 3\n      v5 = 10\n      v6 = 5\n      users = 1\n      play_sdr = 10\n      claimReward_sdr = 10\n    Model language\n      Helena\n    Analysis date\n      December, 24, 2021 at 16:46:25\n    Command used\n      /home/quypham/helena/bin/helena -N=CHECK -p=prop test.lna\n    File path\n      /home/quypham/SolidityProject/tools/unfolding/output/test.lna\n\n  Search report\n  ------------------------------------------------------------------------------\n    Action performed\n      property checking\n    Host machine\n      quypham (pid = 16631)\n    Property checked\n      prop\n    Termination state\n      PROPERTY_HOLDS\n    Options\n      Search algorithm = DFS\n      Partial order reduction = off\n      Hash compaction = off\n      State compression = off\n      Random successor selection = off\n      Hash table size = 4194304 states\n      Worker threads = 1\n\n  Statistics report\n  ------------------------------------------------------------------------------\n\n    Model statistics\n    ----------------------------------------------------------------------------\n      15 places\n      17 transitions\n      62 arcs\n\n    Time statistics\n    ----------------------------------------------------------------------------\n      3.06 s. for source compilation\n      0.04 s. for exploration\n\n    Exploration statistics\n    ----------------------------------------------------------------------------\n      10232 states stored\n      10232 states processed\n      0 accepting states\n      0 deadlock states\n      20463 transitions\n\n    Other statistics\n    ----------------------------------------------------------------------------\n      20463 events executed\n--------------------------------------------------------------------------------\n;"),
]
mycursor.executemany(sqlFomular,multi)
db.commit()